### ISSUE TITLE
Missing plot_reconstruction.py

### ISSUE THREAD

**Issue by PhysicsOfAI** [fwilliams/deep-geometric-prior#3]
The file plot_reconstruction.py seems to be missing.

**Comment by fwilliams** [comment]
Hi, 

That file shouldn't be listed in the documentation as it doesn't exist! I'll remove it from the README.

The proper way to use the DGP code is to first run `reconstruct_surface.py` or `reconstruct_single_patch.py` (see the [README](https://github.com/fwilliams/deep-geometric-prior/blob/master/README.md) for instructions and examples). This file produces a `.pt` file (you specify the name with `-o`, e.g. `-o mymodel` outputs `mymodel.pt`. 

To generate an upsampled pointcloud from the `.pt` file outputted by `reconstruct_surface.py` or `reconstruct_single_patch.py`, you must run `export_point_cloud.py` with the `.pt` file as an argument. `export_point_cloud.py` outputs a `ply` file with a dense point cloud which you can visualize in any software supporting PLY. Run the script with `-h` to see the full set of parameters used to control the upsampled point cloud.
