### ISSUE TITLE
Ground truth surface data

### ISSUE THREAD

**Issue by raphaelsulzer** [fwilliams/deep-geometric-prior#7]
Hi,

thank you for making this great project available!

May I ask where you found the ground truth surfaces of the benchmark (Gargoyle, Quasimoto, Daratech etc.)?

I would like to try out samplings with different scanner options applied to the models, but for this I need the ground truth surfaces.

It seems like they are not directly provided in the benchmark data.

**Comment by fwilliams** [comment]
Hi @raphaelsulzer unfortunately, the surface reconstruction benchmark only comes with dense point clouds for ground truth. See the `ground_truth/` directory in the zip for this paper. 

It would be pretty reasonable to simply mesh the very dense ground truth data and use that as a proxy for the real ground truth data. You can do that as follows with [Point Cloud Utils](https://github.com/fwilliams/point-cloud-utils)
 1. Convert the dense ground truth files from `.xyz` to `.ply` so they're easier to manage (See code below which does this)
 2. Estimate normals for the dense point cloud. (See code below)
 3. Generate a mesh with e.g. [Screened Poisson Surface Reconstruction](http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version8.0/)

#### Estimating normals with point cloud utils:
```python
import point_cloud_utils as pcu
import numpy as np

path_to_ply = "put your path here"
num_neighbors = 20  # Number of nearest neighbors to use for normal estimation. Tune this to control smoothness of normals
v, _, _, _ = pcu.read_ply(path_to_ply, dtype=np.float64)
n = pcu.estimate_normals(v, k=num_neighbors)
pcu.write_ply(path_to_ply[:-len(".ply")] + "-normals.ply, v, np.zeros([0, 3], dtype=np.int32), n.astype(v), np.zeros([0, 3], dtype=v.dtype))
```
#### Converting .xyz to .ply
```python
import argparse
import numpy as np
import point_cloud_utils as pcu

def main():
    argparser = argparse.ArgumentParser()
    argparser.add_argument("xyz_path", type=str)
    args = argparser.parse_args()

    if not args.xyz_path.endswith(".xyz"):
        raise ValueError("Input file must end in .xyz")

    pts = []
    with open(args.xyz_path) as f:
        for line in f:
            pts.append([float(c) for c in line.strip().split()])

    pts = np.array(pts)
    out_path = args.xyz_path[:-len("xyz")] + "ply"
    print(out_path)
    pcu.write_ply(out_path, pts, np.zeros([0, 3], dtype=np.int32),
                  np.zeros([0, 3], dtype=pts.dtype), np.zeros([0, 3], dtype=pts.dtype))


if __name__ == "__main__":
    main()
```

**Comment by raphaelsulzer** [comment]
Ok, I see. Thanks a lot for the explanation and the code! Great help!
